"""
Misaka Cipher - Memory Specification
Data models for episodic memory and core insights
"""

from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
from datetime import datetime


@dataclass
class EpisodicMemory:
    """
    A single episodic memory entry.
    
    Represents a specific event/interaction that occurred in the system.
    Stored with vector embedding for semantic search.
    """
    
    memory_id: str              # MCMEM-YYYYMMDDHHMMSS-HASH
    trace_id: str               # Linked Trace_ID from source interaction
    timestamp: str
    event_type: str             # agent_spawn, tool_forge, request, error, etc.
    domain: str                 # Security, Data, Finance, etc.
    summary: str                # Human-readable summary
    content: str                # Full content/details
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            'memory_id': self.memory_id,
            'trace_id': self.trace_id,
            'timestamp': self.timestamp,
            'event_type': self.event_type,
            'domain': self.domain,
            'summary': self.summary,
            'content': self.content,
            'metadata': self.metadata
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'EpisodicMemory':
        """Create from dictionary."""
        return cls(**data)


@dataclass
class CoreInsight:
    """
    A compressed summary of multiple episodic memories.
    
    Generated by Heartbeat summarization process.
    These are persistent facts that remain even when episodic memories are pruned.
    """
    
    insight_id: str             # MCINS-YYYYMMDD-SESSION#
    timestamp: str
    time_window_start: str
    time_window_end: str
    summary: str                # Natural language summary
    domains_active: List[str]   # Domains involved
    tools_generated: List[str]  # Tools created in this window
    agents_spawned: int         # Number of agents spawned
    trace_ids: List[str]        # Related Trace_IDs
    key_events: List[str]       # Important events
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            'insight_id': self.insight_id,
            'timestamp': self.timestamp,
            'time_window_start': self.time_window_start,
            'time_window_end': self.time_window_end,
            'summary': self.summary,
            'domains_active': self.domains_active,
            'tools_generated': self.tools_generated,
            'agents_spawned': self.agents_spawned,
            'trace_ids': self.trace_ids,
            'key_events': self.key_events,
            'metadata': self.metadata
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'CoreInsight':
        """Create from dictionary."""
        return cls(**data)


def generate_memory_id() -> str:
    """Generate unique memory ID."""
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    import random
    import string
    hash_part = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
    return f"MCMEM-{timestamp}-{hash_part}"


def generate_insight_id(session_number: int = 1) -> str:
    """Generate unique insight ID."""
    date = datetime.now().strftime("%Y%m%d")
    return f"MCINS-{date}-SESSION{session_number}"


# Alias for backward compatibility and CI checks
EpisodicEntry = EpisodicMemory
